# Generated by Django 3.0.2 on 2020-01-04 00:09

import cutter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, validators=[cutter.models.validate_dot_com], verbose_name='Enlace')),
                ('key', models.CharField(max_length=20, unique=True, verbose_name='Clave')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
                'ordering': ['-created'],
            },
        ),
    ]
